repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md,mdx"]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-merge-conflict

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.9.6
    hooks:
      - id: prettier
        entry: prettier --check --ignore-unknown
        additional_dependencies:
          - prettier-plugin-astro

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks
