name = "ukpf-wiki"
compatibility_date = "2026-08-06"

[assets]
directory = "./dist"
not_found_handling = "404-page"

[env.staging]
name = "ukpf-wiki-staging"
main = "worker/index.ts"
workers_dev = true
routes = [
  { pattern = "staging.ukpersonal.finance", custom_domain = true },
]

[env.staging.assets]
directory = "./dist"
not_found_handling = "404-page"
binding = "ASSETS"
run_worker_first = true

[env.production]
name = "ukpf-wiki-production"
routes = [
  { pattern = "ukpersonal.finance", custom_domain = true },
]

[env.production.assets]
directory = "./dist"
not_found_handling = "404-page"

[env.flowchart]
name = "ukpf-flowchart"
routes = [
  { pattern = "flowchart-test.ukpersonal.finance", custom_domain = true },
]

[env.flowchart.assets]
directory = "./flowchart"
not_found_handling = "404-page"
