name = "ukpf-wiki"
compatibility_date = "2026-08-06"

[assets]
directory = "./dist"
not_found_handling = "404-page"

[env.staging]
name = "ukpf-wiki-staging"
main = "worker/index.ts"
routes = [
  { pattern = "staging.ukpersonal.finance", custom_domain = true }
]

[env.staging.assets]
directory = "./dist"
not_found_handling = "404-page"
binding = "ASSETS"

[env.production]
name = "ukpf-wiki-production"
routes = [
  { pattern = "new.ukpersonal.finance", custom_domain = true }
]

[env.production.assets]
directory = "./dist"
not_found_handling = "404-page"
